apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        # image: gcr.io/qwiklabs-gcp-01-1fd61dd0d26d/sample-app:v2.0
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-01-1fd61dd0d26d/my-repository/hello-cloudbuild-dev:v1.0
        ports:
        - containerPort: 8080
